app_data_preparation.R

Monday 04th updates to OOH and A&E datasets

---

app_data_preparation.R

Updated for the latest A&E data from Ewout. Hopefully I've caught all the bits that require updating.
I have left the ae_data2 bits in for now but commented them out in case they are required in future weeks. However I am happy to remove these lines if the data will always come in the same format from now on.
Thanks 😄

Update A&E data

---

app_data_preparation.R

binding new weekly data to old data

addition of 10May2020 OOH data

---

app_data_preparation.R

update RAPID to 10may2020

---

shiny_app/server.R
shiny_app/ui.R

very small changes to intro text based on colins suggestions of 11/05/2020

update intro text with CF edits from 11/05/2020

---

shiny_app/global.R
shiny_app/server.R

additional clarification of NHS 24 data within dashboard and correction of terminology

Nhs24 supplement

---

shiny_app/global.R
shiny_app/server.R

changes to metadata for nhs24 and sas

additional updates to NHS 24 and SaS metadata

---

SW_Records_by_Category.R

Hello Jaime, here is my file.  Let me know if you need any changes. Thanks, Rory.

Gets records from RAPID.

---

shiny_app/server.R

I have added `input$adm_type` to the title of the specialty charts on the hospital admission tab to make clear which type of admission has been selected.

Specialty title

---

app_data_preparation.R

Have updated:
- Filepath to new shiny_input_files folder
- Date of last_week

A&E Update w/e 10/05/20

---

app_data_preparation.R

Have updated:
- Filepath for new shiny_inputs_folder
- Added latest extract
- Updated last_week date

NHS24 w/e 17/05/20

---

app_data_preparation.R

updates to SAS up to 10 may 2020
minor filepath changes so app could run

updates to rapid, OOH up to 17 may 2020

---

app_data_preparation.R
shiny_app/server.R

(+ change of download data column title from pre2020 to 2018-2019 average)

filepaths updates

---

app_data_preparation.R
shiny_app/cardio_tab.R
shiny_app/functions_server.R
shiny_app/global.R
shiny_app/ui.R

Hi Jaime,
As discussed, here the pull request for 'cardio_tab_MM' to 'cardio_tab'.

Cardio tab mm

---

app_data_preparation.R
shiny_app/cardio_tab.R
shiny_app/functions_server.R
shiny_app/global.R
shiny_app/ui.R

Merging `cardio_tab_prescribing` to `cardio_tab`.

Cardio tab prescribing

---

app_data_preparation.R
shiny_app/summary_tab.R

SAS, OOH and RAPID weekly update

SAS, OOH and RAPID weekly update

---

shiny_app/data_tab.R
shiny_app/ui.R

- Updated dropdown list
- Renamed interv and surv 
- Added immunisation data

data tab fix

---

app_data_preparation.R

i've run updates for NHS24 for week ending 14/06/2020 but i've also incorporated some script to compile the historic zipped files into a single 'historic' rds file to remove need for unzipping and to save network folder space.  I'll need to go an delete the historic zipped folder once we're happy the new code works.

nhs24 1506

---

app_data_preparation.R

updates: SAS, AE, rapid, OOH - 15june

---

shiny_app/immunisation_tab.R
shiny_app/ui.R

Just a little branch to add in the immunisation commentary for 17th june publication.  I still want to rework some of the commentary but i'm putting this in now just so the dashboard can go for pra

update immunisation commentary for 17th june update

---

shiny_app/data_tab.R
shiny_app/global.R

Cardiovascular datasets (`ae_cardio`, `cardio_drugs`, `cath_lab`) added to **Data** tab.
Jaime, I have renamed the `lab` variable in the `cath_lab` dataset to `Area name (cath. lab)`  (just for the data tab) as I thought it would be good if it appeared first but I am happy to change it back or change it to something different altogether.

Cardio data

---

app_data_preparation.R

Weekly update of A&E, cardiovascular prescribing and A&E cardio data (week ending 14th June 2020).

Weekly update of A&E, cardiovascular prescribing and A&E cardio data.

---

app_data_preparation.R

should be a fairly simple update...but always worth getting a fresh pair of eyes to double check

update SAS data on22nd june

---

app_data_preparation.R

Weekly update of Cardio Prescribing data - latest data: week ending 21/06

Weekly update; Cardio Prescribing - latest data: week ending 21/06

---

app_data_preparation.R

Hi Vicky,
NHS24 and SAS updates are done.
I haven't done SAS before so let me know if I've missed anything that needs to be updated still.
Lucinda

Ll updates sas nhs24

---

app_data_preparation.R
shiny_app/global.R
shiny_app/perinatal_tab.R
shiny_app/server.R
shiny_app/ui.R

final perinatal tab (as of Friday 26th June)

Perinatal ld

---

app_data_preparation.R

Updates for GP OOH and deaths data. 
Waiting to merge perinatal tab to master for that update.

Updates 29062020 ld

---

app_data_preparation.R
shiny_app/perinatal_tab.R

Minor edits to text based on SG comments
Column header changes in download data

Perinatal edits 30062020

---

shiny_app/data_tab.R
shiny_app/global.R

Hi Vicky,
I have updated the scripts so that the data tab shows the table data for child health and immunisations rather than the scurve data. 
I'm not sure whether to include this in this weeks release or wait until the data is updated next week. Let me know what you think, we can hold off on merging with the master if we decide to wait until next week.
Lucinda

child health and imms data tab based on table data (not scurve)

---

app_data_preparation.R

Weekly update for A&E, A&E Cardio and Prescribing - data up to 28/06/2020.

Update for A&E, A&E Cardio and Prescribing.

---

app_data_preparation.R

Rapid, SAS, OOH, deaths updates

---

app_data_preparation.R

Hi Jaime,
Apologies for bothering you once more. I have run the extract in BOXI and added the NHS24 data to the dashboard. It all looks OK to me but obviously having a second pair of eyes look over it is always best ..

Weekly NHS24 update - data up to 05/07/2020

---

shiny_app/data_tab.R
shiny_app/global.R

Just noticed that the existing child health data tabs were not working after the update to the data.
I have also added the two new child health reviews too.

child health data tab fix

---

app_data_preparation.R
functions_packages_data_prep.R

Moving packages, functions etc to a different script
Function to create immunisations and child health review tables
Reducing some duplication of code with hb lookups

Simplification of data script

---

shiny_app/global.R

removing legacy p_perinatal_table and u_perinatal_table as not needed

removing legacy p_perinatal_table and u_perinatal_table as not needed

---

shiny_app/data_tab.R
shiny_app/global.R

Not sure if this is quite right/if we want more columns from the raw data included?

Addition of perinatal data to data tab

---

app_data_preparation.R
functions_packages_data_prep.R

Updates 20th July

---

app_data_preparation.R

Weekly update of Deaths, Prescribing and NHS24:
- Deaths: data up to 12/07/2020
- Prescribing: data up to 12/07/2020
- NHS24: data up to 19/07/2020

Wkly upd deaths nhs24 presc

---

app_data_preparation.R
extract_rapid_data.R

Summary of changes:
- SAS and RAPID sections of data prep script have been updated.
- Extracts have been added to the correct folders.
- Extract rapid script required SIMD lookup to be updated.

SAS and RAPID

---

app_data_preparation.R
shiny_app/cardio_tab.R
shiny_app/server.R
shiny_app/ui.R

PCI by admission urgency code, although not incorporated at the end (but if we change our minds we can always recover it).
Also small updated of cardiac procedure data for GJ and starting with OOH (but data issues for last week there)

PCI urgency

---

app_data_preparation.R

Hi Jaime,
As discussed, I have completed the weekly update for "Prescribing" with data up to 26th July 2020.

Prescribing update. Data up to 26/07/2020

---

shiny_app/child_health_tab.R

small fix as HV data download not currently working in live app

fix hv data download

---

app_data_preparation.R

Hi Laura,
I have run both the rapid extract script and the NHS 24 BOXI query and have updated the app_data_preparation script accordingly.
Thanks 😄

NHS 24 and Rapid (24/08)

---

app_data_preparation.R
functions_packages_data_prep.R
shiny_app/cardio_tab.R

Weekly update for A&E, A&E Cardio and Prescribing. Data up to 23/08/20.

Wkly upd ae cardioae presc

---

app_data_preparation.R
shiny_app/perinatal_tab.R
shiny_app/server.R
shiny_app/ui.R

addition of july data to perinatal tab

Perinatal 19aug

---

app_data_preparation.R
shiny_app/functions_server.R
shiny_app/global.R
shiny_app/immunisation_tab.R
shiny_app/server.R
shiny_app/ui.R

still some issues with update but want to compare the code with master

Imms update aug

---

app_data_preparation.R
extract_rapid_data.R

Updates ld 31aug

---

app_data_preparation.R

Updated for latest file name and end date

Updated file name and end date

---

app_data_preparation.R

ooh, mh ooh, sas, nhs24 updates

Ve upd2809

---

app_data_preparation.R
functions_packages_data_prep.R

Weekly updates: A&E, A&E cardio, A&E MH, OOH MH and RAPID

Weekly updates: A&E, A&E cardio, A&E MH, OOH MH and RAPID

---

app_data_preparation.R
shiny_app/ui.R

updates for ooh, nhs24, sas, rx cardio and rx mh.  I've also removed the comment about ooh data correction from the front page of the dashboard as i'm not sure if we want to keep it so prominent?

Updates ve0411

---

app_data_preparation.R
shiny_app/breastfeeding_tab.R
shiny_app/child_dev_tab.R
shiny_app/child_health_tab.R
shiny_app/data_tab.R
shiny_app/functions_server.R
shiny_app/global.R

As discussed, this pull request contains the usual update of the app_data_preparation.R file but also some further updates to include HSCP in data downloads and remove weekly data from health visitor s-curve.
Updated commentary to come.

Child Health Updates 04 Nov

---

app_data_preparation.R
final_app_files.R
functions_packages_data_prep.R
shiny_app/data_tab.R
shiny_app/global.R

Trying to reduce time that we have to rerun the data prep scripts and make it easier for other people to collaborate in the project. It will mean that we will have to update the final_app_files when we update a dataset, but it should work for when we are preparing preview versions too.  What do you think?

New data prep
